// <auto-generated />
namespace B_M.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddPayment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPayment));
        
        string IMigrationMetadata.Id
        {
            get { return "202510310244450_Add Payment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
