// <auto-generated />
namespace B_M.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddProductLinkBrand : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProductLinkBrand));
        
        string IMigrationMetadata.Id
        {
            get { return "202510302151437_Add Product-Link-Brand"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
